name: Feature Request
description: File a feature request
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: input
    id: feature_summary
    attributes:
      label: Feature Summary
    validations:
      required: true
  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed Description
    validations:
      required: true
