version: "3.4"
services:

  cuttle-server:
    container_name: cuttle-server
    environment:
      - CUTTLE_DOCKERIZED=true
      - VITE_API_URL=0.0.0.0:1337
      - VITE_BUILD_OUTPUT=assets
    # No env file because docker is different :)
    # env_file:
    build:
      context: ..
      dockerfile: ./docker/.Dockerfile
    command: npm run start:server
    ports:
      - "1337:1337"
    volumes:
      - ../src/:/cuttle/src/

  cuttle-client:
    container_name: cuttle-client
    environment:
      - CUTTLE_DOCKERIZED=true
      - VITE_API_URL=localhost:8080
      - VITE_BUILD_OUTPUT=assets
    # No env file because docker is different :)
    # env_file:
    build:
      context: ..
      dockerfile: ./docker/.Dockerfile
    command: npm run start:client
    ports:
      - "8080:8080"
      - "8098:8098"
    volumes:
      - ../src/:/cuttle/src/
    depends_on:
      - cuttle-server

