name: 'Test: End-To-End'

on:
  workflow_call:
    secrets:
      record-key:
        required: true
      github-token:
        required: true

jobs:
  # Install & build frontend
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: assets

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: assets

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          parallel: true
          start: npm start
          config-file: cypress.config.js
          # wait for 2 minutes for the server to respond
          wait-on: 'http://localhost:1337'
          wait-on-timeout: 120

        env:
          VITE_API_URL: http://localhost:1337
          CYPRESS_RECORD_KEY: ${{ secrets.record-key }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.github-token }}
