name: 'Test: End-To-End'

on:
  workflow_call:
    secrets:
      record-key:
        required: true
      github-token:
        required: true

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build:gamestate
          record: true
          parallel: false
          start: npm run start:server:gamestate
          config-file: cypress.config.js
          # wait for 2 minutes for the server to respond
          wait-on: 'http://localhost:1337'
          wait-on-timeout: 120

        env:
          VITE_API_URL: http://localhost:1337
          CYPRESS_RECORD_KEY: ${{ secrets.record-key }}
          VITE_USE_GAMESTATE_API: 'true'
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.github-token }}
